### ISSUE TITLE
Running helloworld.py on Solo gives exception, but runs fine locally

### ISSUE THREAD

**Issue by DarylWM** [3drobotics/solodevguide#286]
Wondering if anybody has come across this exception when running helloworld.py on Solo? The script finishes, but raises the exception on shutdown. The script runs fine locally.

...
 Mode: LOITER
 Is Armable?: False
 Armed: False
Done.
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 504, in run
  File "/log/solo-script/env/lib/python2.7/site-packages/dronekit/mavlink.py", line 89, in mavlink_thread_out
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 504, in run
  File "/log/solo-script/env/lib/python2.7/site-packages/dronekit/mavlink.py", line 129, in mavlink_thread_in
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'

**Comment by hamishwillee** [comment]
Thanks @DarylWM Yes, this is a known issue.

**Comment by alexblack** [comment]
+1

**Comment by pjbca** [comment]
Does this prevent connection on running the script again?
I am getting sporadic connection between the python script running on solo, and the vehicle.
A typical error is:
  File "/home/root/opt/my_python_code/env/lib/python2.7/site-packages/dronekit/__init__.py", line 2142, in wait_ready
    timeout)
dronekit.APIException: wait_ready experienced a timeout after 30 seconds.

**Comment by keyurrakholiya** [comment]
i am facing same problem.suggest help

**Comment by janthony** [comment]
I am struggling with the same issue. Any proposed workaround for the time being?

**Comment by tasarmiento** [comment]
Did anyone find a solution to this issue?  I'm seeing it with my own scripts running onboard Solo.
